DROP table IF EXISTS users,items,requests,bookings,comments,requests CASCADE;

create table IF NOT EXISTS users
(
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) UNIQUE,
    email varchar(65) UNIQUE
);

create table if not exists requests
(
    request_id int generated by default as identity primary key,
    description varchar(255),
    user_id int references users(user_id),
    status varchar(10),
    created_date_time TIMESTAMP WITHOUT TIME ZONE
);

create table if not exists items
(
    item_id int generated by default as identity primary key,
    name varchar(40),
    description varchar(255),
    available boolean,
    user_id int references users(user_id),
    request_id int references requests(request_id)
);

create table if not exists bookings
(
    booking_id int generated by default as identity primary key,
    booking_start TIMESTAMP WITHOUT TIME ZONE,
    booking_finish TIMESTAMP WITHOUT TIME ZONE,
    item_id int references items(item_id),
    user_id int references users(user_id),
    status varchar(20)
);

create table if not exists comments
(
    comment_id int generated by default as identity primary key,
    text varchar(255),
    comment_day_time timestamp without time zone,
    user_id int references users(user_id),
    item_id int references items(item_id)
);

create table if not exists requests
(
    request_id int generated by default as identity primary key,
    description varchar(255),
    user_id int references users(user_id)
)






